volumes:
  lrr_contents:

services:

  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s

  lanraragi:
    image: ghcr.io/psilabs-dev/lanraragi:dev-0.9.30-53dc4d85820e549532d265a7859b3636871b38ca
    container_name: lanraragi
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - "LRR_REDIS_ADDRESS=redis:6379"
      - LRR_UID=${MY_UID}
      - LRR_GID=${MY_GID}
    volumes:
      - lrr_contents:/home/koyomi/lanraragi/content:rw
    depends_on:
      redis:
        condition: service_healthy
