services:

  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s
    profiles:
      - server

  lanraragi:
    image: ghcr.io/psilabs-dev/lanraragi:cr-dev-0.9.30-9774bbbfca497efa85d8c27d6b32490cc1bc8324
    container_name: lanraragi
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - "LRR_REDIS_ADDRESS=redis:6379"
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - server
